zeo:
  restart: always
  build: zeo
  user: "1000"
  volumes_from:
   - data

zclient1:
  restart: always
  image: eeacms/glossary-zclient
  user: "1000"
  links:
   - zeo

zclient2:
  restart: always
  image: eeacms/glossary-zclient
  user: "1000"
  links:
   - zeo

zclient3:
  restart: always
  image: eeacms/glossary-zclient
  user: "1000"
  links:
   - zeo

varnish:
  restart: always
  image: eeacms/varnish:4
  links:
   - zclient1
   - zclient2
   - zclient3
  volumes:
   - ./varnish/conf.d/:/etc/varnish/conf.d/
   - ./varnish/500msg.html:/var/static/500msg.html
  env_file:
   - ./varnish/varnish.env

apache:
  restart: always
  image: eeacms/httpd:centos6
  links:
   - varnish
  volumes:
   - ./apache/vh-glossary.conf:/etc/httpd/conf.d/vh-glossary.conf
  ports:
   - "2222:80"

data:
  build: data
  volumes:
   - /var/local/zeostorage/var/
