apache:
  restart: always
  image: eeacms/glossary-apache
  links:
  - varnish
  ports:
  - "2222:80"

varnish:
  restart: always
  image: eeacms/glossary-varnish
  links:
  - zclient1
  - zclient2
  - zclient3
  environment:
  - CACHE_SIZE=200M
  - PARAM_VALUE=-p default_ttl=3600 -p default_grace=3600

zeo:
  restart: always
  image: eeacms/glossary-zeoserver
  user: "1000"
  volumes_from:
  - data

zclient1:
  restart: always
  image: eeacms/glossary-zclient
  user: "1000"
  links:
  - zeo

zclient2:
  restart: always
  image: eeacms/glossary-zclient
  user: "1000"
  links:
  - zeo

zclient3:
  restart: always
  image: eeacms/glossary-zclient
  user: "1000"
  links:
  - zeo

data:
  image: busybox
  volumes:
  - /var/local/zeostorage/var/
  command: chown -R 1000:1000 /var/local/zeostorage/var/
