zeo:
  build: zeo
  user: 1000
  volumes_from:
   - data

zclient:
  image: eeacms/glossary-zclient
  user: 1000
  links:
   - zeo
  ports:
   - "8080:8080"

data:
  build: data
  volumes:
   - /var/local/zeostorage/var/
