apache:
  restart: always
  image: eeacms/glossary-apache
  links:
  - varnish
  ports:
  - "2222:80"
  volumes:
  - /etc/localtime:/etc/localtime:ro

varnish:
  restart: always
  image: eeacms/glossary-varnish
  links:
  - zclient1
  - zclient2
  - zclient3
  environment:
  - CACHE_SIZE=200M
  - PARAM_VALUE=-p default_ttl=3600 -p default_grace=3600
  volumes:
  - /etc/localtime:/etc/localtime:ro

zeo:
  restart: always
  image: eeacms/glossary-zeoserver
  volumes_from:
  - data
  volumes:
  - /etc/localtime:/etc/localtime:ro

zclient1:
  restart: always
  image: eeacms/glossary-zclient
  links:
  - zeo
  volumes:
  - /etc/localtime:/etc/localtime:ro

zclient2:
  restart: always
  image: eeacms/glossary-zclient
  links:
  - zeo
  volumes:
  - /etc/localtime:/etc/localtime:ro

zclient3:
  restart: always
  image: eeacms/glossary-zclient
  links:
  - zeo
  volumes:
  - /etc/localtime:/etc/localtime:ro

data:
  image: busybox
  volumes:
  - /var/local/zeostorage/var
  command: ["chown", "-v", "-R", "500:500", "/var/local/zeostorage/var"]
  tty: true
  stdin_open: true
