zeo:
  build: zeo
  user: "1000"
  volumes_from:
  - data

zclient:
  build: zclient
  user: "1000"
  links:
  - zeo
  ports:
  - "80:8080"

data:
  image: busybox
  volumes:
  - /var/local/zeostorage/var/
  command: chown -R 1000:1000 /var/local/zeostorage/var/
