zeo:
  build: zeo
  user: 1000
  volumes_from:
   - data

zclient1:
  image: eeacms/glossary-zclient
  user: 1000
  links:
   - zeo

zclient2:
  image: eeacms/glossary-zclient
  user: 1000
  links:
   - zeo

zclient3:
  image: eeacms/glossary-zclient
  user: 1000
  links:
   - zeo

varnish:
  build: varnish
  links:
   - zclient1
   - zclient2
   - zclient3

apache:
  build: apache
  links:
   - varnish
  ports:
   - "80:80"

data:
  build: data
  volumes:
   - /var/local/zeostorage/var/
